config/routes.rb
MinhaProva::Application.routes.draw do  
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :tests

  resources :disciplines

  resources :courses

  resources :colleges

  resources :teachers

  resources :questions

  resources :level_questions

  root "home#index"
  devise_for :users

  

  

end

app/models/discipline.rb
# == Schema Information
#
# Table name: disciplines
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  course_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Discipline < ActiveRecord::Base
  belongs_to :course
  has_many :tests
  has_and_belongs_to_many :questions
  
  validates :name, presence: true
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @disciplines = Discipline.all
  end

  def show
  end

  def new
    @discipline = Discipline.new
  end

  def edit
  end

  def create
    @discipline = Discipline.new(discipline_params)
      if @discipline.save
        flash[:success] = "Disciplina salva com sucesso!"
        redirect_to @discipline
      else
        render "new"
      end
  end

  def update
    if @discipline.update(discipline_params)
      flash[:success] = "Disciplina atualizada com sucesso!"
      redirect_to @discipline
    else
      render "edit"
    end
  end

  def destroy
    @discipline.destroy
    redirect_to disciplines_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:name, :description, :college_id, :teacher_id, :course_id)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<%= simple_form_for(@discipline) do |f| %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.association :course %>

  <%= f.button :submit, "Enviar" %>
  
<% end %>

app/views/disciplines/edit.html.erb
<h1>Editando disciplina</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @discipline, class: "btn" %> |
<%= link_to 'Voltar', disciplines_path, class: "btn" %>

app/views/disciplines/index.html.erb
<h1>Listando disciplines</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Professor</th>
      <th>Curso</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.name %></td>
        <td><%= discipline.description %></td>
        <td><%= discipline.course.name %></td>
        <td nowrap>
          <%= link_to "", rails_admin.show_path(model_name: 'discipline', id: discipline.id), :class => "glyphicon glyphicon-eye-open", title: "Visualizar"  %>
          <%= link_to "", rails_admin.edit_path(model_name: 'discipline', id: discipline.id), :class => "glyphicon glyphicon-edit", title: "Editar" %>
          <%= link_to "", discipline_path(discipline), title: "Deletar", :method => :delete, :confirm => "Tem certeza que deseja remover essa disciplina?", :class => "glyphicon glyphicon-trash" %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Disciplina', rails_admin.new_path('discipline'), class: "btn btn-primary ico-plus" %>

app/views/disciplines/new.html.erb
<h1>Nova disciplina</h1>

<%= render 'form' %>

<%= link_to 'Voltar', disciplines_path, class: "btn" %>

app/views/disciplines/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @discipline.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @discipline.description %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @discipline.teacher.name %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @discipline.course.name %>
</p>

<%= link_to 'Editar', edit_discipline_path(@discipline), class: "btn" %> |
<%= link_to 'Voltar', disciplines_path, class: "btn" %>