config/routes.rb
MinhaProva::Application.routes.draw do  
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :tests

  resources :disciplines

  resources :courses

  resources :colleges

  resources :teachers

  resources :questions

  resources :level_questions

  root "home#index"
  devise_for :users

  

  

end

app/models/teacher.rb
# == Schema Information
#
# Table name: teachers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  course_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Teacher < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_and_belongs_to_many :colleges
  has_many :tests

  validates :name, :user_id, :course_id, presence: true
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @teachers = Teacher.all
  end

  def show
  end

  def new
    @teacher = Teacher.new
  end

  def edit
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      flash[:success] = "Professor criado com sucesso!"
      redirect_to @teacher
    else
      render "new"
    end
  end

  def update
    if @teacher.update(teacher_params)
      flash[:success] = "Professor atualizado com sucesso!"
      redirect_to @teacher
    else
      render "edit"
    end
  end

  def destroy
    @teacher.destroy
    redirect_to teachers_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :user_id, :course_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= simple_form_for(@teacher, html: { role: "form"  }) do |f| %>
  <%= f.input :name %>
  <%= f.association :user, prompt: "Escolha um usuário" %>
  <%= f.association :course, prompt: "Escolha um curso" %>

  <%= f.button :submit, class: "btn btn-primary", value: "Cadastrar" %>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Listando Professores</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email de usuário</th>
      <th>Curso</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.user ? teacher.user.email : "Ainda não existe um email cadastrado" %></td>
        <td><%= teacher.course ? teacher.course.name : "Ainda não pertence a nenhum curso" %></td>
        <td nowrap>

          <%= link_to "", rails_admin.show_path(model_name: 'teacher', id: teacher.id), :class => "glyphicon glyphicon-eye-open", title: "Visualizar"  %>
          <%= link_to "", rails_admin.edit_path(model_name: 'teacher', id: teacher.id), :class => "glyphicon glyphicon-edit", title: "Editar" %>
          <%= link_to "", teacher_path(teacher), title: "Deletar", :method => :delete, :confirm => "Tem certeza que deseja remover esse professor?", :class => "glyphicon glyphicon-trash" %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo professor', rails_admin.new_path('teacher'), class: "btn btn-primary ico-plus" %>

app/views/teachers/new.html.erb
<h1>Novo Professor</h1>

<%= render 'form' %>

<%= link_to 'Voltar', teachers_path, class: "btn" %>

app/views/teachers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @teacher.user.name %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @teacher.course.name %>
</p>

<%= link_to 'Editar', edit_teacher_path(@teacher) %> |
<%= link_to 'Voltar', teachers_path %>