config/routes.rb
MinhaProva::Application.routes.draw do  
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :tests

  resources :disciplines

  resources :courses

  resources :colleges

  resources :teachers

  resources :questions

  resources :level_questions

  root "home#index"
  devise_for :users

  

  

end

app/models/college.rb
# == Schema Information
#
# Table name: colleges
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  city       :string(255)
#  state      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class College < ActiveRecord::Base
	has_and_belongs_to_many :teachers
	has_many :courses

  validates :name, :city, :state, presence: true
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @colleges = College.all
  end

  def show
  end

  def new
    @college = College.new
  end

  def edit
  end

  def create
    @college = College.new(college_params)
    if @college.save
      flash[:success] = "Universidade criada com sucesso"
      redirect_to @college
    else
      render "new"
    end
  end

  def update
    if @college.update(college_params)
      flash[:success] = "Universidade atualizada com sucesso!"
      redirect_to @college
    else
      render "edit"
    end
  end

  def destroy
    @college.destroy
    redirect_to colleges_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name, :city, :state)
    end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/_form.html.erb
<%= simple_form_for(@college) do |f| %>
  <%= f.input :name %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.button :submit, "Enviar", class: "btn btn-primary" %>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editando Universidade</h1>

<%= render 'form' %>

<%= link_to 'visualizar', @college, class: "btn" %> |
<%= link_to 'Voltar', colleges_path, class: "btn" %>

app/views/colleges/index.html.erb
<h1>Listando Universidades</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= college.city %></td>
        <td><%= college.state %></td>
        <td class="nowrap">
          <%= link_to '', rails_admin.show_path(model_name: 'college', id: college.id), class: "glyphicon glyphicon-eye-open", title: "Visualizar" %>
          <%= link_to '', rails_admin.edit_path(model_name: 'college', id: college.id), class: "glyphicon glyphicon-edit", title: "Editar" %>
          <%= link_to '', college, title: "Remover", method: :delete, class: "glyphicon glyphicon-trash", data: { confirm: 'Você tem certeza que deseja remover essa universidade?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Universidade', new_college_path, class: "btn btn-primary ico-plus" %>

app/views/colleges/new.html.erb
<h1>Nova universidade</h1>

<%= render 'form' %>

<%= link_to 'Voltar', colleges_path, class: "btn" %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @college.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @college.state %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>