config/routes.rb
MinhaProva::Application.routes.draw do  
  
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  resources :tests

  resources :disciplines

  resources :courses

  resources :colleges

  resources :teachers

  resources :questions

  resources :level_questions

  root "home#index"
  devise_for :users

  

  

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  question_id :integer
#  option_id   :integer
#  correct     :boolean
#  created_at  :datetime
#  updated_at  :datetime
#

class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :option

  validates :option_id, :question_id, presence: true

  before_create :characterize_answer

  def correct?
    self.correct || self.option.correct?
  end

  private

  def characterize_answer
    if option.correct?
      self.correct = true
    end
  end
end

app/models/college.rb
# == Schema Information
#
# Table name: colleges
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  city       :string(255)
#  state      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class College < ActiveRecord::Base
	has_and_belongs_to_many :teachers
	has_many :courses

  validates :name, :city, :state, presence: true
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  college_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Course < ActiveRecord::Base
  belongs_to :college
  has_many :teachers
  has_many :disciplines

  validates :name, :college_id, presence: true
end

app/models/discipline.rb
# == Schema Information
#
# Table name: disciplines
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  course_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Discipline < ActiveRecord::Base
  belongs_to :course
  has_many :tests
  has_and_belongs_to_many :questions
  
  validates :name, presence: true
end

app/models/level_question.rb
# == Schema Information
#
# Table name: level_questions
#
#  id          :integer          not null, primary key
#  value       :integer
#  question_id :integer
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class LevelQuestion < ActiveRecord::Base
  belongs_to :question, inverse_of: :level_questions
  belongs_to :user

  validates :value, :user_id, presence: true
  validates :value, numericality: true

  def value_enum
    [1,2,3,4,5]
  end
end

app/models/option.rb
# == Schema Information
#
# Table name: options
#
#  id          :integer          not null, primary key
#  question_id :integer
#  text        :string(255)
#  correct     :boolean
#  created_at  :datetime
#  updated_at  :datetime
#

class Option < ActiveRecord::Base
  belongs_to :question, inverse_of: :options

  scope :correct, -> {where(:correct => true) }
  scope :incorrect, -> {where(:correct => false) }

  def to_s
    self.text
  end

  def correct?
    self.correct == true
  end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id               :integer          not null, primary key
#  description      :text
#  user_id          :integer
#  created_at       :datetime
#  updated_at       :datetime
#  question_type_id :integer
#  average          :float
#

class Question < ActiveRecord::Base

  belongs_to :user, inverse_of: :questions
  belongs_to :question_type
  

  has_many :options
  has_many :level_questions
  has_and_belongs_to_many :tests
  has_and_belongs_to_many :disciplines

  accepts_nested_attributes_for :options,
    :reject_if => ->(a) { a[:text].blank? },
      :allow_destroy => true

  accepts_nested_attributes_for :level_questions    

  validates :description, presence: true, allow_blank: false
  validates :user_id, presence: true

  def correct_options
    options.correct
  end

  def incorrect_options
    options.incorrect
  end

  def average
    self.level_questions.average('value').to_f
  end

  def self.from_level(level, limit)
    int_level = level.to_int
    questions = Question.select { |q| q.average.between?(int_level, int_level+1) }
    questions.sample(limit)
  end

end

app/models/question_type.rb
# == Schema Information
#
# Table name: question_types
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class QuestionType < ActiveRecord::Base
  validates :name, presence: true
end

app/models/teacher.rb
# == Schema Information
#
# Table name: teachers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  course_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Teacher < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_and_belongs_to_many :colleges
  has_many :tests

  validates :name, :user_id, :course_id, presence: true
end

app/models/test.rb
# == Schema Information
#
# Table name: tests
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  discipline_id :integer
#  created_at    :datetime
#  updated_at    :datetime
#  level         :float
#  user_id       :integer
#  num_questions :integer
#

class Test < ActiveRecord::Base
	belongs_to :user
	belongs_to :discipline

  has_and_belongs_to_many :questions

  scope :for_user, -> (id) { where(user_id: id) }

  validates :discipline_id, :user_id, :level, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#

class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	has_one :teacher     
  has_many :questions, inverse_of: :user
  validates :email, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def formata_data(data)
    # formatando a data: Aug, 31 2007 - 9:55PM
    data.strftime("%m, %b %Y - %H:%M")
  end

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success" # Green
      when :error
        "alert-danger" # Red
      when :alert
        "alert-warning" # Yellow
      when :notice
        "alert-info" # Blue
      else
        flash_type.to_s
    end
  end
  
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
# encoding: utf-8

module QuestionsHelper
  def set_question_rate_color(question_rate)
    question_rate = Float(question_rate)
    if(question_rate > 1.0 && question_rate <= 2.5)
      "success"
    elsif (question_rate > 2.5 && question_rate <= 4.0)
      "warning"
    else
      "danger"
    end
  end

  def user_evaluated_question?(question_id)
    LevelQuestion.where(user_id: current_user.id, question_id: question_id).count > 0
  end

  def get_user_avaliation_for_question(question_id)
    LevelQuestion.where(user_id: current_user.id, question_id: question_id).first.try(:value).to_f
  end

  def show_options_for_average_select
    [["Muito fácil", 1..2], ["Fácil", 2..3], ["Médio", 3..4], ["Dificil", 4..5], ["Muito dificil", 5..6]]
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="footer-menu">
      <nav class="container">
        <h2 class="title-footer">suporte e ajuda</h2>
        <ul class="no-liststyle">
          <li><a href="mailto:gurgel.renan@gmail.com?Subject=MinhaProva[Contato]" target="_top" class="bg-customer-support"><span class="visible-lg">Contato</span></a></li>
        </ul>
      </nav>
    </div>
    <div class="container footer-info">
      <p class="copy-right">Copyright © 2013 Renan Gurgel</p>
    </div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-46904745-1', 'minhaprova.com.br');
  ga('send', 'pageview');

</script>
</footer>

app/views/layouts/_header.html.erb
<header class="header" role="banner">
  <div class="container">
    <span class="control-menu hidden visible-xs ico-menu-2"></span>
    <span class="control-sidebar hidden visible-xs ico-list"></span>
    <h1 class="project-name"><%= link_to "Minha Prova", root_path %></h1>
    <a href="#" class="help-sugestions ico-question hidden-xs">Ajuda e Sugestões</a>

    <div class="dropdown hidden-xs">
      <% if user_signed_in? %>
      <a href="#" data-toggle="dropdown" class="title-dropdown"><%= current_user.email %></a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><%= link_to "#{current_user.email}", teacher_path(current_user.teacher), role: "menu-item" %></li>
        <li><%= link_to "Logout", destroy_user_session_path, role: "menu-item", :method => :delete  %></li>
      </ul>
      <% else %>
        <li><%= link_to "Cadastre-se", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>    
      <% end %>
    </div>
  </div>
</header>

  <div class="nav-content">
    <menu class="menu">
      <ul class="container">
        <li><a href="/" class="<%= 'active' if params[:controller] == 'home' %> ico-home" role="menuitem">Home</a></li>
        <li><%= link_to "Questões", questions_path, role: "menu-item", class: params[:controller] == 'questions' ? 'active' : '' %></li>
        <li><%= link_to "Universidades", colleges_path, role: "menu-item", class: params[:controller] == 'colleges' ? 'active' : '' %></li>
        <li><%= link_to "Cursos", courses_path, role: "menu-item", class: params[:controller] == 'courses' ? 'active' : '' %></li>
        <li><%= link_to "Disciplinas", disciplines_path, role: "menu-item", class: params[:controller] == 'disciplines' ? 'active' : '' %></li>
        <li><%= link_to "Provas", tests_path, role: "menu-item", class: params[:controller] == 'tests' ? 'active' : '' %></li>
      </ul>
    </menu>
  </div>

app/views/layouts/_sidebar.html.erb
<aside class="sidebar col-md-3" role="complementary">
  <section class="sidebox">
    <h1 class="sidebox-title ico-bars">Dados do sistema</h1>
    <div class="sidebox-inner">
      <span class="status-text">
        Quantidade de colaboradores
        <strong><%= User.count %></strong>
      </span>
      <hr>
      <span class="status-text">
        Quantidade de cursos
        <strong><%= Course.count %></strong>
      </span>
    </div>
    <div class="well well-sm well-status-sidebar txt-center no-margin-bottom">
      <p>Total de questões no sistema</p>
      <b><%= Question.count %></b>
    </div>
  </section>

  <section class="sidebox">
    <h1 class="sidebox-title ico-flag">Dicas</h1>
    <div id="carousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active sidebox-inner">
          <h2 class="title-6">Crie questões (3C)</h2>
          <p>Acesse a área restrita e crie questões para aumentar a colaboração do sistema</p>
        </div>
        <!-- <div class="item sidebox-inner">
          <h2 class="title-6">Cuidado com os bounces 2</h2>
          <p>Bounces são tipos diversos de problemas que impedem que um contato receba a mensagem enviada.</p>
          <p>Por exemplo: e-mail inválido, caixa postal cheia, lentidão no servidor do destinatário, etc.</p>
        </div> -->
      </div>
      <div class="carousel-nav">
        <a href="#carousel" class="left carousel-control ico-direction-left" data-slide="prev"></a>
        <b>1</b> de <i>1</i>
        <a href="#carousel" class="right carousel-control ico-direction-right" data-slide="next"></a>
      </div>
    </div>
  </section>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br" class="color-blue">
<head>
  <title>MinhaProva</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta charset="utf-8">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucid">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <!-- TODO: Try load this css via aplication.css -->
  <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="http://assets.locaweb.com.br/locastyle/2.0.0-a4/stylesheets/locastyle.css">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <main class="main">
    <div class="container">
      <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type) %> fade in">
          <button class="close" data-dismiss="alert">×</button>
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= debug params %>
    </div>
  </main>

  <%= render "layouts/footer" %>

</body>
</html>